Prefix: '[PathFinding]'
Enable:
  DragonCore: false
  #是否使用Dragoncore显示导航路径提示
  #否则用导航使用粒子来显示路径提示
  Debug: false
  #是否启用Debug提示
  #开启后每次路径导航都会提示一些关键信息
  ActionBar: true
  #是否启用actionbar导航提示
  Hologram: true
  #是否启用全息导航提示
  Title: true
  #是否启用title导航提示
  AutoMode: false
  #是否启用自动选择模式
  #启用后请配置Base配置下的AutoDistance
Base:
  Mode: 1
  #0 - 曼哈顿距离
  #1 - 欧氏距离
  #效率: 曼哈顿距离 > 欧式距离
  #精确度: 欧式距离 > 曼哈顿距离
  OpenNodeLimit: 600
  #最大队列中可探索路径点数量限制
  #如果路径计算中OpenNode节点数量超过该值就结束计算
  #debug模式下导航可以提示本次导航路径计算中OpenNode节点数量
  AutoDistance: 500
  #起点到终点的直线距离超过多远则使用曼哈顿模式
Tips:
  ActionBar: '&a距离目标位置还有 %s% M'
  Hologram:
    - '[item]STONE'
    - '[text]&f距离 %s% M'
  Title:
    Theme: '&a【导航系统】'
    Sub: '&7正在为你导航'