name: Pathfinding
main: com.taylorswiftcn.megumi.pathfinding.Pathfinding
version: ${project.version}
author: 'Megumi'
api-version: '1.13'
depend:
  - MegumiLib
  - ProtocolLib
softdepend:
  - DragonCore
  - Citizens
  - HolographicDisplays

commands:
  pf:
    description: show all command